### ISSUE TITLE
Couldn't get where and how to start with existing react and electron project?

### ISSUE THREAD

**Issue by OnlinePage** [toonvanvr/electron-transparency-mouse-fix#18] opened 2022-11-16 16:15 UTC
Hi, first of all nice package, I am planning to integrate this package within my `react-electron` app, but couldn't get where to start? could you please guide on this?

**Comment by toonvanvr** [comment] 2022-11-22 19:03
Hi, this repo is quite outdated, so I wouldn't advise you to use this code right now. If I (ever) make a stable version again, I'll respond to this post.

You can reproduce the behaviour manually in a simple way:
Setting CSS `pointer-events: none` makes your mouse events have the `<html>` tag as target.
Set `ignoreMouseEvents(true, {forward: true})` if you hit the html tag, else set it to false.
The annoying bit it that since a couple of years, you need to pass this message through the IPC in or to keep your electron app secure. If you disable all security, a basic version can be implemented in a couple of lines. Then there are differences between mac/windows/linux and even OS updates broke functionality more than once.

**Comment by toonvanvr** [comment] 2022-11-22 21:33
Your comment made me check out the `v2` branch of this library. It seems to work on Windows, but will definitely have some quirks if you start dragging and dropping. I'll work on improving the demo the coming hours.

```sh
npm run dev:demo
```

I haven't published a build of this library yet, so for now you'll have follow these steps to use it in your code:

```sh
git clone https://github.com/toonvanvr/electron-transparency-mouse-fix
cd electron-transparency-mouse-fix
npm install
npm run build:lib
```

Then import it like in the [`/demo`](https://github.com/toonvanvr/electron-transparency-mouse-fix/tree/v2/demo) folder. The annoying bit is the `preload.js` script which needs to be compiled because `require()` is partially disabled for security reasons in newer Electron releases. Check out [`build:demo:preload`](https://github.com/toonvanvr/electron-transparency-mouse-fix/blob/96f576ab03c901ef3bb64232f053b4861ef088c1/package.json#L11) how I did it for my repo. This will be custom for yours. In essence, it replaces the `require('lib/...')` with the code itself. Your react-electron repo might have this workaround preconfigured, else you can try to copy my workflow as a step in your build process. Important is having it not replace `require('electron')`, which rollup accomplishes with the `-e electron` flag. 

The demo is barebones and logs to the console. Enabling `new BrowserWindow({ alwaysOnTop: true })` will make it easier to recognize that the library works.

![image](https://user-images.githubusercontent.com/2529712/203425237-d8ec8172-5ba9-4cfd-aa25-028856576d90.png)

**Comment by OnlinePage** [comment] 2022-11-28 19:02
> Your comment made me check out the `v2` branch of this library. It seems to work on Windows, but will definitely have some quirks if you start dragging and dropping. I'll work on improving the demo the coming hours.
> 
> ```shell
> npm run dev:demo
> ```
> 
> I haven't published a build of this library yet, so for now you'll have follow these steps to use it in your code:
> 
> ```shell
> git clone https://github.com/toonvanvr/electron-transparency-mouse-fix
> cd electron-transparency-mouse-fix
> npm install
> npm run build:lib
> ```
> 
> Then import it like in the [`/demo`](https://github.com/toonvanvr/electron-transparency-mouse-fix/tree/v2/demo) folder. The annoying bit is the `preload.js` script which needs to be compiled because `require()` is partially disabled for security reasons in newer Electron releases. Check out [`build:demo:preload`](https://github.com/toonvanvr/electron-transparency-mouse-fix/blob/96f576ab03c901ef3bb64232f053b4861ef088c1/package.json#L11) how I did it for my repo. This will be custom for yours. In essence, it replaces the `require('lib/...')` with the code itself. Your react-electron repo might have this workaround preconfigured, else you can try to copy my workflow as a step in your build process. Important is having it not replace `require('electron')`, which rollup accomplishes with the `-e electron` flag.
> 
> The demo is barebones and logs to the console. Enabling `new BrowserWindow({ alwaysOnTop: true })` will make it easier to recognize that the library works.
> 
> ![image](https://user-images.githubusercontent.com/2529712/203425237-d8ec8172-5ba9-4cfd-aa25-028856576d90.png)



Hi thanks for the reply, been busy on other stuff. Btw as mentioned above I followed along and Voila!! it works😃, but quite weirdly , by default it doesn't accept any click on any element (that's okay, but..) it doesn't even allows click through. Second if any element is added `etmf-accept` class then it only allows click on that particular element(that's good). But click through isn't occurring. Am I doing something wrong?🤔
Here is my electron `main.js` file.

`
    
    // ./public/electron.js
    const path = require("path");
    const { app, BrowserWindow, ipcMain } = require("electron");
    const isDev = require("electron-is-dev");
    const npath = require("node:path");
    const {
      EtmfMain,
    } = require("../electron-transparency-mouse-fix-2/lib/dist/electron/etmf-main");

    

    let win = null;
    function createWindow() {
      // Create the browser window.
      win = new BrowserWindow({
        width: 1920,
        height: 1080,
        fullscreen: true,
        transparent: true,
        frame: false,
        alwaysOnTop: true,
        webPreferences: {
          nodeIntegration: false,
          contextIsolation: true,
          enableRemoteModule: false,
          preload: path.join(__dirname, "../MypreloadCompiled.js"),
        },
      });
      // win.loadFile("index.html");
      win.loadURL(
        isDev
          ? "http://localhost:3000"
          : `file://${path.join(__dirname, "../build/index.html")}`
      );
      // Open the DevTools.
      // if (isDev) {
      //   win.webContents.openDevTools({ mode: "undocked" });
      // }

      win.webContents.on("did-fail-load", function () {
        console.log("did-fail-load");

        win.loadURL(
          isDev
            ? "http://localhost:3000"
            : `file://${path.join(__dirname, "../build/index.html")}`
        );
      });
    }
    new EtmfMain({ log: console.log, fixPointerEvents: "auto" });// added after I recognize that it was missing
    app.whenReady().then(createWindow);
    app.on("window-all-closed", () => {
      if (process.platform !== "darwin") {
        app.quit();
      }
    });

    app.on("activate", () => {
      if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
      }
    });
    // ipc.on('redirect', function(){
    // win.loadUrl('http://192.168.1.10/page2')  // SECOND WEBPAGE
    // });
    // End of the file
    // ipcMain.on(channels.GET_DATA, (event, arg) => {
    //   const { product } = arg;
    //   console.log(product);
    // });

`

**Comment by OnlinePage** [comment] 2022-11-30 09:43
> Your comment made me check out the `v2` branch of this library. It seems to work on Windows, but will definitely have some quirks if you start dragging and dropping. I'll work on improving the demo the coming hours.
> 
> ```shell
> npm run dev:demo
> ```
> 
> I haven't published a build of this library yet, so for now you'll have follow these steps to use it in your code:
> 
> ```shell
> git clone https://github.com/toonvanvr/electron-transparency-mouse-fix
> cd electron-transparency-mouse-fix
> npm install
> npm run build:lib
> ```
> 
> Then import it like in the [`/demo`](https://github.com/toonvanvr/electron-transparency-mouse-fix/tree/v2/demo) folder. The annoying bit is the `preload.js` script which needs to be compiled because `require()` is partially disabled for security reasons in newer Electron releases. Check out [`build:demo:preload`](https://github.com/toonvanvr/electron-transparency-mouse-fix/blob/96f576ab03c901ef3bb64232f053b4861ef088c1/package.json#L11) how I did it for my repo. This will be custom for yours. In essence, it replaces the `require('lib/...')` with the code itself. Your react-electron repo might have this workaround preconfigured, else you can try to copy my workflow as a step in your build process. Important is having it not replace `require('electron')`, which rollup accomplishes with the `-e electron` flag.
> 
> The demo is barebones and logs to the console. Enabling `new BrowserWindow({ alwaysOnTop: true })` will make it easier to recognize that the library works.
> 
> ![image](https://user-images.githubusercontent.com/2529712/203425237-d8ec8172-5ba9-4cfd-aa25-028856576d90.png)



Okay so I found why not the click through was working, it was because I had missed `new EtmfMain({ log: console.log, fixPointerEvents: "auto" });` object creation. Now click through is working along with click accepted on elements with `etmf-accept` but the issue is after few click or more it is lost i.e. only click through occurs and elements doesn't accepts clicks.

**Comment by toonvanvr** [comment] 2022-12-01 14:21
Hi, thanks for the details. I will check it out in a couple hours.

**Comment by OnlinePage** [comment] 2022-12-02 21:25
> Hi, thanks for the details. I will check it out in a couple hours.

Finally got what and where it is causing issue, so if u load the electron and the react page (as of above) and that is delayed in loading, then in such cases it fails after bit to properly handle the click through.
specially when the page is loaded via `win.loadURL("http://localhost:blablaa)"` and electron had to wait or reload the page. But if the page is build and then loaded or if u have directly loaded the page with `win.loadFile(`index.html')`  , then it's perfect over there and works flawlessly, also along with `awlaysOnTop:true` , it is working 😍.

So finally tried and tested that on windows your module V2(with above steps) works perfectly.👍 thanks @toonvanvr 🙏

**Comment by toonvanvr** [comment] 2022-12-02 21:33
I think it's a matter of initializing after React populates the page then, but it's been a while so I don't remember the lifecycle hooks you can use in React.

**Comment by toonvanvr** [comment] 2022-12-02 21:51
@OnlinePage I checked again and understand the issue. Your case indeed isn't supported, this needs to be fixed in the library by splitting the preloader into an elevated rights 'api' which is accessed from normal scripts on your page. I'm not sure if the `window.etmf` instance which is set in the preloader using `contextBridge.exposeInMainWorld('etmf', ...)` remains accessible after navigation (`window.loadURL`), but I assume it does.

The problem is that this preloader will only run once and injects itself into the first page that you load. Quite dumb of me not to have foreseen that 😉. Maybe calling `window.etmf.disable(); window.etmf.enable()` consecutively is a workaround that works for now. The API will change before v2 is released then, but no ETA since I keep forgetting about this project. You can spam me to work on it. 👍

**Comment by OnlinePage** [comment] 2022-12-04 13:31
Well that's good!! Again, a gentle reminder to work on this project!😃⏰
Btw, I think that in the not too distant future, this module will serve as a time saver for many electron enthusiasts!

**Comment by toonvanvr** [comment] 2023-03-16 22:34
Hi @OnlinePage, I think Tauri is the right successor for Electron nowadays. I'm not going to work any further on this library given that there's so much more interesting stuff to work on now.

**Closed as completed by toonvanvr** 2023-03-16 22:34 UTC
Labels: bug
