### ISSUE TITLE
Demo freeze system on Ubuntu

### ISSUE THREAD

**Issue by vanvuongngo** [toonvanvr/electron-transparency-mouse-fix#6] opened 2019-10-25 14:02 UTC
Does not work on Ubuntu
```
> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

**Comment by toonvanvr** [comment] 2019-10-28 19:42
What do you mean with freeze?

I'll try it out in a VM, but don't know if it will emulate bugs correctly due to  no HW accelleration.

**Comment by toonvanvr** [comment] 2019-10-28 20:28
I just checked it in a 19.10 VM with the 1.0.0rc1 from npmjs.

Electron 4 (=time it got developed): works like it used to
Electron 7 (=current): does not work -- will try to get it to work in v2 which is not ready yet

Closing util there's more info to reproduce.

**Closed as completed by toonvanvr** 2019-10-28 20:28 UTC
